from nltk.sentiment import SentimentIntensityAnalyzer

class CybersecuritySentimentAnalyzer:
    def __init__(self):
        self.sia = SentimentIntensityAnalyzer()
        self.sia.lexicon = {}
        self.cybersecurity_lexicon = {
            'vulnerability': -2.0,
            'exploit': -3.5,
            'patch': 2.5,
            'hack': -3.0,
            'h4ck': -3.0,
            'secure': 3.5,
            'breach': -4.0,
            'protect': 3.0,
            'malware': -4.0,
            'ransomware': -4.5,
            'ransom': -4.5,
            'demanding': -1.0,
            'encryption': 2.0,
            'backdoor': -3.5,
            'firewall': 2.5,
            'phishing': -3.5,
            'ph1shing': -3.5,
            'authentication': 2.5,
            'threat': -3.0,
            'zero-day': -4.0,
            '0day': -4.0,
            'oday': -4.0,
            'nday': -4.0,
            'security': 2.5,
            'attack': -3.0,
            'defense': 3.0,
            'compromise': -3.5,
            'mitigation': 2.0,
            'data-leak': -4.0,
            'adversary': -3.0,
            'incident': -2.5,
            'intrusion': -3.5,
            'DDoS': -3.0,
            'cyberattack': -3.5,
            'spyware': -4.0,
            'rootkit': -4.0,
            'whitelist': 2.0,
            'blacklist': -2.0,
            'vulnerability scan': 1.5,
            'penetration test': 1.0,
            'threat actor': -3.5,
            'multi-factor authentication': 3.0,
            'mfa': 3.0,
            'spear-phishing': -4.0,
            'security awareness': 2.5,
            'privilege escalation': -3.5,
            'brute force': -3.5,
            'SQL injection': -4.0,
            'sqli': -4.0,
            'social engineering': -3.5,
            'APT': -4.0,
            'insider threat': -4.0,
            'zero trust': 2.5,
            'SIEM': 2.0,
            'SOC': 2.0,
            'incident response': 2.0,
            'cyber hygiene': 2.0,
            'fuzzing': 1.0,
            'CVE': -2.0,
            'keylogger': -4.0,
            'XSS': -3.5,
            'whaling': -4.0,
            'data breach': -4.5,
            'breached': -2.5,
            'malicious code': -4.5,
            'trojan': -4.0,
            'worm': -4.0,
            'virus': -4.0,
            'botnet': -4.5,
            'root access': -4.0,
            'exfiltration': -4.5,
            'network sniffing': -3.5,
            'ransomware attack': -4.5,
            'cryptojacking': -4.0,
            'denial of service': -3.5,
            'data poisoning': -4.0,
            'man-in-the-middle': -4.0,
            'DNS spoofing': -3.5,
            'email spoofing': -3.5,
            'SQL injection attack': -4.5,
            'session hijacking': -4.0,
            'cross-site scripting': -4.0,
            'server compromise': -4.0,
            'network attack': -4.0,
            'encrypted': 1.5,
            'credential stuffing': -3.5,
            'URL phishing': -3.5,
            'fake software update': -4.0,
            'social engineering attack': -4.0,
            'security vulnerability': -3.5,
            'attack vector': -3.5,
            'endpoint protection': 2.5,
            'data encryption': 2.5,
            'security policy': 2.0,
            'security patch': 2.5,
            'incident management': 2.0,
            'security audit': 2.0,
            'data integrity': 2.5,
            'forensic analysis': 2.5,
            'system hardening': 2.5,
            'access control': 2.0,
            'cybersecurity training': 2.5,
            'vulnerability management': 2.0,
            'penetration testing': 1.5,
            'threat intelligence': 2.5,
            'digital forensics': 2.5,
            'risk assessment': 2.0,
            'network segmentation': 2.5,
            'patch management': 2.5,
            'security architecture': 2.5,
            'data masking': 2.0,
            'secure coding': 2.0,
            'compliance': 2.0,
            'privacy policy': 2.0,
            
            # Terms related to trading/buying/selling:
            'caller': -4.0,
            'insider': -1.5,
            'cb hitters': -5.0,
            'launder': -4.0,
            'logs': -1.5,
            'buying': -0.5,
            'selling': -0.5,
            'swapper': -5.0,
            'swapping': -5.0,
            'credit ': -4.0,
            'card': -1.0,
            'sim swap': -5,
            'swaping': -5,
            'bank': -1,
            'log': -1,
            'drainer': -4,
            'looking': -1,
            'bank': -1,
            'cloned': -4,
            'tap in': -5,
            'verizon': -4,
            'at&t': -4,
            'inny': -3,
            'callers': -4,
            'cb': -1,
            'coinbase': -3,
            'panel': -2,
            'drain': -5,
            
            # Sensitive terms:
            'cp': -5.0,
            'child porn': -5.0,
            'cheese pizza': -3.0
        }

        self.sia.lexicon.update(self.cybersecurity_lexicon)

    def polarity_scores(self, text):
        return self.sia.polarity_scores(text)

    def get_constants(self):
        return self.sia.constants()

    def update_lexicon(self, word, score):
        self.cybersecurity_lexicon[word] = score
        self.sia.lexicon.update(self.cybersecurity_lexicon)
